-- 50 conceitos C_TS452, distribuídos proporcionalmente ao peso das 8 áreas
-- Pesos: Procurement 18 | Master Data 15 | IM 12 | Sources+IV 12 | Valuation 11 | MRP 11 | Optimization 11 | Clean Core/Fiori 10

-- ============ Enterprise Structure & Master Data (15%) — 8 conceitos ============
INSERT INTO concepts (area, weight_pct, title, production_rule, fiori_app_name, work_case_ref) VALUES
('Enterprise Structure & Master Data', 15, 'Hierarquia organizacional MM',
 'SE precisa definir onde estoque e compras acontecem ENTÃO mandante > empresa > centro > depósito; a organização de compras se liga a empresa OU a centros.',
 NULL, 'T024W com 5 orgs de compras no 5520 travou a determinação de INCO1/MODFRETE'),
('Enterprise Structure & Master Data', 15, 'Org. de compras cross-plant vs específica',
 'SE a org. de compras NÃO está atribuída a nenhuma empresa ENTÃO ela pode comprar para centros de empresas diferentes (compras corporativas).',
 NULL, NULL),
('Enterprise Structure & Master Data', 15, 'Tipo de material: o que ele controla',
 'SE precisa definir faixa de numeração, telas/visões e atualização de quantidade/valor por centro ENTÃO isso vem do TIPO de material, não do grupo de mercadorias.',
 'Manage Product Master Data', NULL),
('Enterprise Structure & Master Data', 15, 'Visões do mestre por nível organizacional',
 'SE o dado é de compras ou MRP ENTÃO é mantido no nível CENTRO; SE é contábil ENTÃO no nível da área de avaliação.',
 'Manage Product Master Data', NULL),
('Enterprise Structure & Master Data', 15, 'Business Partner para fornecedores',
 'SE criar fornecedor ENTÃO é um BP com papéis FLVN00 (finanças/empresa) e FLVN01 (compras/org. de compras); BP bloqueado trava o processo inteiro.',
 'Maintain Business Partner', 'BP bloqueado travando fluxo E-Kanban na VWCO'),
('Enterprise Structure & Master Data', 15, 'Registro info de compras',
 'SE quer preço e condições determinados automaticamente na PO ENTÃO precisa existir info record fornecedor+material+org (ME11).',
 'Manage Purchasing Info Records', 'ME11 ausente p/ CASTERTECH em 3 materiais → erro CFOP 8B148 (IR31731687)'),
('Enterprise Structure & Master Data', 15, 'Lista de fontes (source list)',
 'SE precisa fixar, bloquear ou restringir fornecedor por período ENTÃO source list; o indicador de MRP define se a fonte é usada no planejamento.',
 'Manage Source Lists', NULL),
('Enterprise Structure & Master Data', 15, 'Dados mestres incompletos quebram o fluxo adiante',
 'SE um campo de controle do mestre está vazio (ex.: tipo de estoque na entrada) ENTÃO o erro só aparece etapas depois, no documento que depende dele.',
 NULL, 'INSMK vazio em MARC p/ 5 materiais bloqueou 341 documentos no fluxo AF (~R$2M/dia)'),

-- ============ Procurement Processes (18%) — 9 conceitos ============
('Procurement Processes', 18, 'Ciclo procure-to-pay completo',
 'SE comprar material ENTÃO PR → PO → GR → IV; cada documento referencia o anterior e herda seus dados.',
 'Manage Purchase Requisitions', NULL),
('Procurement Processes', 18, 'Estratégia de liberação de PR/PO',
 'SE o valor do documento atinge a estratégia (classe + características) ENTÃO bloqueio até liberação com código e grupo de liberação.',
 'My Inbox', NULL),
('Procurement Processes', 18, 'Subcontratação (categoria de item L)',
 'SE PO com categoria L ENTÃO os componentes ficam em "estoque com fornecedor" e o GR do produto acabado consome os componentes via movimento 543.',
 'Manage Purchase Orders', 'Caso CFOP 8B148 subcontratação CASTERTECH no centro 5500'),
('Procurement Processes', 18, 'Consignação (categoria de item K)',
 'SE categoria K ENTÃO o estoque fica no seu depósito mas é do FORNECEDOR; o passivo só nasce na retirada e a liquidação é sem fatura (MRKO).',
 NULL, NULL),
('Procurement Processes', 18, 'Transferência entre centros com STO',
 'SE transferir entre centros com documento de compras ENTÃO Stock Transport Order (UB/NB); em 2 passos: 351 na saída + 101 na chegada.',
 'Manage Purchase Orders', NULL),
('Procurement Processes', 18, 'Efeitos da entrada de mercadorias (GR)',
 'SE GR com 101 referenciando PO ENTÃO nasce doc de material + doc contábil (débito estoque BSX / crédito GR-IR WRX) + histórico da PO atualizado.',
 'Post Goods Receipt for Purchasing Document', NULL),
('Procurement Processes', 18, 'Revisão de faturas com 3-way match',
 'SE a fatura diverge de PO/GR além da tolerância ENTÃO a fatura é lançada mas BLOQUEADA para pagamento (status R).',
 'Create Supplier Invoice', NULL),
('Procurement Processes', 18, 'Compras de serviços',
 'SE comprar serviço ENTÃO o aceite da folha de registro de serviços FAZ o papel do GR.',
 'Manage Service Entry Sheets - Lean Services', NULL),
('Procurement Processes', 18, 'Devolução ao fornecedor',
 'SE devolver mercadoria de uma PO ENTÃO item de retorno na PO ou movimento 122 referenciando o documento de material original.',
 NULL, NULL),

-- ============ Inventory Management (12%) — 6 conceitos ============
('Inventory Management', 12, 'Tipos de movimento essenciais',
 'SE entrada por PO ENTÃO 101 (estorno 102); devolução 122; consumo p/ ordem 261; transferência entre depósitos 311; entrada inicial 561.',
 'Post Goods Movement', NULL),
('Inventory Management', 12, 'Tipos de estoque e disponibilidade',
 'SE material entra em Controle de Qualidade (QI) ENTÃO NÃO está disponível para consumo/MRP; liberar com transferência QI → utilização livre (321).',
 'Manage Stock', 'INSMK vazio mandava tudo p/ estoque errado — 341 docs travados no fluxo AF'),
('Inventory Management', 12, 'Transferência em 1 passo vs 2 passos',
 'SE precisa enxergar o estoque em trânsito ENTÃO 2 passos (313/315 entre depósitos, 303/305 entre centros); SE não ENTÃO 1 passo.',
 NULL, NULL),
('Inventory Management', 12, 'Inventário físico',
 'SE contagem diverge do sistema ENTÃO a diferença é lançada com referência ao documento de inventário, ajustando estoque e contabilidade.',
 'Process Physical Inventory Count Results', NULL),
('Inventory Management', 12, 'Reservas',
 'SE existe saída futura planejada ENTÃO a reserva reduz o estoque DISPONÍVEL (ATP) sem movimentar nada fisicamente.',
 NULL, NULL),
('Inventory Management', 12, 'Estrutura do documento de material',
 'SE lançou movimento ENTÃO cabeçalho + itens (antigo MKPF/MSEG, hoje MATDOC); nem todo movimento gera documento contábil (ex.: 311 mesmo centro).',
 'Material Documents Overview', 'J_1BEXBASE=0 no item do doc de material travou INSERT da NF de subcontratação'),

-- ============ Valuation & Account Determination (11%) — 5 conceitos ============
('Valuation & Account Determination', 11, 'Preço médio móvel (V) vs standard (S)',
 'SE preço V ENTÃO o GR ajusta o preço médio com o valor da PO; SE preço S ENTÃO a diferença vai para conta de diferenças (PRD).',
 NULL, NULL),
('Valuation & Account Determination', 11, 'Determinação automática de contas (OBYC)',
 'SE lançamento de estoque ENTÃO conta = chave de transação (BSX estoque, WRX GR/IR, GBB contrapartidas, PRD diferenças) + classe de avaliação.',
 NULL, NULL),
('Valuation & Account Determination', 11, 'Classe de avaliação',
 'SE materiais do mesmo tipo precisam de contas contábeis diferentes ENTÃO a classe de avaliação no mestre (visão Contabilidade) decide.',
 'Manage Product Master Data', NULL),
('Valuation & Account Determination', 11, 'Avaliação dividida (split valuation)',
 'SE o mesmo material tem valores distintos por origem/qualidade ENTÃO tipos de avaliação separados, com estoque e preço por tipo.',
 NULL, NULL),
('Valuation & Account Determination', 11, 'Material Ledger no S/4HANA',
 'SE S/4HANA ENTÃO Material Ledger é OBRIGATÓRIO; o custeio real (actual costing) é que continua opcional.',
 NULL, NULL),

-- ============ Consumption-Based Planning / MRP (11%) — 5 conceitos ============
('Consumption-Based Planning (MRP)', 11, 'Tipos de MRP: PD vs ponto de reabastecimento',
 'SE planejamento determinístico ENTÃO PD; SE por consumo ENTÃO VB (ponto manual) ou VM (ponto calculado automaticamente pelo sistema).',
 NULL, NULL),
('Consumption-Based Planning (MRP)', 11, 'Tamanho de lote',
 'SE lote exato da necessidade ENTÃO EX; SE quantidade fixa ENTÃO FX; SE agrupar necessidades do período ENTÃO WB/MB.',
 NULL, NULL),
('Consumption-Based Planning (MRP)', 11, 'MRP Live no S/4HANA',
 'SE rodar MRP no S/4 ENTÃO MRP Live direto no HANA; acompanhar cobertura e exceções pelos apps de monitoramento, não por lista estática.',
 'Monitor Material Coverage', NULL),
('Consumption-Based Planning (MRP)', 11, 'Resultado do planejamento',
 'SE o MRP encontra falta ENTÃO gera ordem planejada ou requisição; ordem planejada pode ser convertida em PR/PO conforme o elemento.',
 'Manage Material Coverage', NULL),
('Consumption-Based Planning (MRP)', 11, 'Ponto de reabastecimento e estoque de segurança',
 'SE estoque disponível cai ABAIXO do ponto de reabastecimento ENTÃO o MRP dispara suprimento; ROP = demanda no lead time + estoque de segurança.',
 NULL, NULL),

-- ============ Purchasing Optimization (11%) — 5 conceitos ============
('Purchasing Optimization', 11, 'Contrato por quantidade vs por valor',
 'SE o limite do acordo é quantidade ENTÃO contrato MK; SE é valor total ENTÃO WK; o consumo acontece via pedidos de liberação (release orders).',
 'Manage Purchase Contracts', NULL),
('Purchasing Optimization', 11, 'Programa de remessas (scheduling agreement)',
 'SE entregas recorrentes programadas ENTÃO LP/LPA com divisões de remessa; LPA usa documentação de divisão (forecast/JIT).',
 'Manage Purchase Scheduling Agreements', 'Fluxo E-Kanban VWCO roda sobre programa de remessas'),
('Purchasing Optimization', 11, 'Quota (quota arrangement)',
 'SE dividir a demanda entre várias fontes por percentual ENTÃO quota arrangement, que o MRP respeita na atribuição de fonte.',
 NULL, NULL),
('Purchasing Optimization', 11, 'Criação automática de PO',
 'SE flag de PO automática no material E no fornecedor + fonte válida com preço ENTÃO a PR vira PO sem intervenção do comprador.',
 NULL, NULL),
('Purchasing Optimization', 11, 'Técnica de condições em compras',
 'SE formar preço na PO ENTÃO esquema de cálculo com condições (PB00/PBXX); condições de cabeçalho rateiam entre itens.',
 NULL, NULL),

-- ============ Sources of Supply & Invoice Verification (12%) — 6 conceitos ============
('Sources of Supply & Invoice Verification', 12, 'Prioridade na determinação de fonte',
 'SE várias fontes válidas ENTÃO a ordem é: quota > source list > contrato/programa de remessas > info record.',
 'Assign and Process Purchase Requisitions', NULL),
('Sources of Supply & Invoice Verification', 12, 'Bloqueio de fatura e liberação',
 'SE divergência de preço, quantidade, data ou bloqueio estocástico ENTÃO fatura com status R; liberar centralizadamente após resolver a causa.',
 'Release Blocked Invoices', NULL),
('Sources of Supply & Invoice Verification', 12, 'ERS (liquidação automática do GR)',
 'SE flag ERS no fornecedor E no info record ENTÃO a fatura é gerada automaticamente a partir do GR, sem fatura do fornecedor.',
 NULL, NULL),
('Sources of Supply & Invoice Verification', 12, 'Débito e crédito posterior',
 'SE custo adicional chega DEPOIS da fatura (ex.: frete extra) ENTÃO débito posterior: muda valor, NUNCA quantidade.',
 'Create Supplier Invoice', NULL),
('Sources of Supply & Invoice Verification', 12, 'Conta transitória GR/IR',
 'SE GR e IV não batem ENTÃO sobra saldo na WRX; regularizar saldos antigos com a manutenção da conta GR/IR (MR11).',
 NULL, NULL),
('Sources of Supply & Invoice Verification', 12, 'Custos de frete planejados',
 'SE frete planejado como condição na PO ENTÃO pode ser faturado para um TERCEIRO (transportadora) na revisão de faturas.',
 NULL, 'Determinação INCO1/MODFRETE no 5520 via enhancement em LJ1BFF01 (fallback VWPA)'),

-- ============ Managing Clean Core & SAP Fiori/UX + RISE (10%) — 6 conceitos ============
('Clean Core & SAP Fiori/UX', 10, 'Fiori Launchpad: como achar as coisas na prova',
 'SE precisa de um app na prova ENTÃO buscar pelo NOME do app na busca do Launchpad, não pelo código de transação; apps vivem em spaces e pages.',
 NULL, NULL),
('Clean Core & SAP Fiori/UX', 10, 'Tipos de app Fiori',
 'SE executa um processo ENTÃO app transacional; SE mostra KPI agregado ENTÃO analítico; SE consulta um objeto ENTÃO object page/fact sheet.',
 NULL, NULL),
('Clean Core & SAP Fiori/UX', 10, 'Clean core e extensibilidade',
 'SE precisa customizar mantendo clean core ENTÃO key-user extensibility (in-app) ou side-by-side no BTP; modificação do standard é o que se evita.',
 'Custom Fields', NULL),
('Clean Core & SAP Fiori/UX', 10, 'RISE with SAP',
 'SE mover para a nuvem com contrato único ENTÃO RISE: S/4HANA Cloud + BTP + infraestrutura + serviços num bundle só.',
 NULL, NULL),
('Clean Core & SAP Fiori/UX', 10, 'Situation Handling',
 'SE o sistema deve avisar exceções proativamente (contrato vencendo, quantidade em risco) ENTÃO situações standard configuráveis notificam o responsável.',
 'Manage Situation Types', NULL),
('Clean Core & SAP Fiori/UX', 10, 'Embedded analytics',
 'SE relatório em tempo real dentro do processo ENTÃO CDS views e analytics embutidos no S/4, sem extrair para um BW separado.',
 NULL, NULL);
